CREATE TABLE game_sales
(
    ID           INTEGER PRIMARY KEY,
    GAME_NO      INTEGER,
    GAME_NAME    VARCHAR(32),
    GAME_CODE    VARCHAR(10),
    TYPE         INTEGER,
    COST_PRICE   DECIMAL(5, 2),
    TAX          DECIMAL(5, 3),
    SALE_PRICE   DECIMAL(6, 2),
    DATE_OF_SALE DATETIME,
    CREATED_DATE TIMESTAMP,
    CREATED_BY   VARCHAR(32),
    UPDATED_DATE TIMESTAMP,
    UPDATED_BY   VARCHAR(32)
);